// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpxujnzhapnvnxtewfpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndweHVqbnpoYXBudm54dGV3ZnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjkzNDEsImV4cCI6MjA2NzUwNTM0MX0.wsLXC1xfNFi3t-YEO6c9JJyXprYm5SB2wBKnXbzwF9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});